### ISSUE TITLE
Implement Scene Hierarchy

### ISSUE THREAD

**Issue by Kein** [ManlyMarco/RuntimeUnityEditor#9]
A simple hierarchy tree. You can start walking of scene.RootObjects, they preserve hierarchy, and then populate with the rest of the objects loaded dynamically.

**Comment by ManlyMarco** [comment]
Can you elaborate on what exactly you are suggesting? This sounds exactly like the current object tree view.

**Comment by Kein** [comment]
Yeah, my bad, you do no preserve scene order, you just fetch all parentless and start from there. scene.GetSceneRootObjects() usually returns root objects in the same order as it was saved in scene (implementation detail). I guess a custom tree view would be nice, without sorting.

I have a question though - what is private dependency `mcs_custom` and how did you manage to forward/marshall dependencies by referencing just UnityEngine base assembly? I can't seems to do that in MSVS2019, it wasnt all Unity modules. Did you just merge all unity modules/assemblies into big one for the simplicity's sake?

**Comment by ManlyMarco** [comment]
Root objects are sorted because of them being constantly updated. They could randomly change places, making the list unusable https://github.com/ManlyMarco/RuntimeUnityEditor/blob/master/RuntimeUnityEditor/ObjectTree/ObjectTreeViewer.cs#L511-L525

GetSceneRootObjects isn't used at all for the initial gathering of object because it does not show all objects, so the order can't be maintained https://github.com/ManlyMarco/RuntimeUnityEditor/blob/master/RuntimeUnityEditor/ObjectTree/ObjectTreeViewer.cs#L103-L109

mcs_custom is this https://github.com/kkdevs/mcs - basically a port of roslyn-level mcs with all new language features to .Net 2.0

You have to reference UnityEngine.dll from Unity 5.x, before it was split. The current UnityEngine.dll forwards all of the split types into the respective dll files, so doing this allows runtime editor to run on any Unity version.

**Comment by Kein** [comment]
Can you elaborate on `They could randomly change places, making the list unusable`? I see that you are doing linq sort few times per frame (because you call it from OnGUI which can update few time per frame) so I already found source of my 1fps. But I'm not sure what do you mean by:
> because of them being constantly updated
If you cache the hierarchy you dont have to care about them being updated, just output a stub for the "null" ones and this will give user a clue to fetch new cache. Realtime update is not possible due to the fact we are limited to the main thread unlike Unity Editor (it's UI is multithreaded). You can't make functional real-time hierarchy, sadly. I tried RuntimeEditor on some recent pixel-platformer and I could even move few pixel without getting framelocked by constant GO list update and sort and then GarbageCollector also joined the party every frame.

Kinda sucks  I will have to redo the UI too, I just wanted to rewrite caching.

**Comment by ManlyMarco** [comment]
In some games I tested the calls to GetSceneRootObjects returned objects in a different order in some conditions, which made the list jump all over the place. It's also not very practical to have the objects not be ordered by name.

In that case just disable the automatic updating, just add a simple toggle to where the check for SceneManager feature is made. When disabled it will only poll root objects when the UI is opened, so just press F12 twice to update.
